Repository ROCm/rocBLAS, pull requests merged in 2024-05, with the labels that each got.

#1423 Hotfix: Tune aldebaran BBS TN, TT (#2203)
  library/src/blas3/Tensile/Logic/asm_full/aldebaran/aldebaran_Cijk_Alik_Bjlk_BBS_BH.yaml
  library/src/blas3/Tensile/Logic/asm_full/aldebaran/aldebaran_Cijk_Alik_Bljk_BBS_BH.yaml
  library/src/blas3/Tensile/Logic/asm_full/aldebaran/equality/aldebaran_Cijk_Alik_Bljk_BBS_BH.yaml
Labels: ci:extended

#1432 Hotfix: rocBLAS failure during stream capture
  library/src/rocblas_auxiliary.cpp
Labels: noExtendedCI

#1433 update CHANGELOG.md for ROCm 6.1.2
  CHANGELOG.md
Labels: noCI
