Repository ROCm/rocBLAS, pull requests merged in 2024-06, with the labels that each got.

#1437 Hotfix: Documentation for Bitwise reproducibility from develop
  docs/how-to/what-is-rocblas.rst
Labels: noCI, noExtendedCI

#1438 Hotfix: Update rocblas_set_stream() to check the capture status of new stream
  library/src/include/handle.hpp
  library/src/rocblas_auxiliary.cpp
Labels: noExtendedCI

#1443 Hotfix for 6.2
  library/src/blas3/Tensile/Logic/asm_full/aquavanjaram942/aquavanjaram942_Cijk_Ailk_Bjlk_BSS_BH.yaml
  library/src/blas3/Tensile/Logic/asm_full/aquavanjaram942/aquavanjaram942_Cijk_Ailk_Bjlk_HSS_BH.yaml
Labels: gfx942
