Repository ROCm/rocBLAS, pull requests merged in 2024-10, with the labels that each got.

#1485 Add gfx1151 to 6.2
  CHANGELOG.md
  CMakeLists.txt
  library/src/handle.cpp
  library/src/include/handle.hpp
  tensile_tag.txt
Labels: ci:extended, noHipblasLT

#1491 New sizes tuned for ZGEMM_NN on gfx90a
  library/src/blas3/Tensile/Logic/asm_full/aldebaran/aldebaran_Cijk_Ailk_Bljk_ZB.yaml
Labels: noHipblasLT

#1498 [Docs] Cherry pick - Bump rocm-docs-core from 1.8.1 to 1.8.2 in /docs/sphinx (#2725)
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: ci:docs-only

#1505 fixes random failures in ILP64 iamax iamin (#2738)
  clients/gtest/blas1_gtest.yaml
  library/src/src64/blas1/rocblas_iamax_iamin_kernels_64.cpp
  library/src/src64/blas1/rocblas_iamax_iamin_kernels_64.hpp
Labels: ci:extended, noHipblasLT

#1506 remove Unreleased from CHANGELOG.md
  CHANGELOG.md
Labels: ci:docs-only
