Repository ROCm/rocBLAS, pull requests merged in 2024-09, with the labels that each got.

#1471 math-ci: use precheckin for hipblas-common/hipblaslt dependencies
  .jenkins/common.groovy
Labels: ci:extended

#1484 [Hotfix] Add CI NoHipblasLT flag (#2709)
  .jenkins/common.groovy
  .jenkins/debug.groovy
  .jenkins/extended.groovy
  .jenkins/multigpu.groovy
  .jenkins/precheckin.groovy
  .jenkins/staticanalysis.groovy
  .jenkins/weekly.groovy
Labels: noHipblasLT

#1488 compress code objects (#2707)
  cmake/build-options.cmake
  library/CMakeLists.txt
  rmake.py
Labels: noHipblasLT

#1489 iamin iamax eliminate passes for workspace size reduction (#2711)
  clients/gtest/blas1_gtest.yaml
  library/src/blas1/rocblas_reduction.hpp
  library/src/src64/blas1/rocblas_iamax_iamin_kernels_64.cpp
  library/src/src64/blas1/rocblas_iamax_iamin_kernels_64.hpp
Labels: noHipblasLT

#1493 Cherry-pick to release-staging/rocm-rel-6.3: Update three links to point to official ROCm docs rather than the com…
  .github/CONTRIBUTING.rst
Labels: ci:docs-only

#1487 Updated 6.2.1 changelog so that it reflects the 6.2.1 RN
  CHANGELOG.md
Labels: ci:docs-only

#1494 Fix link to device memory allocation in contributing doc 6.2 version
  CONTRIBUTING.rst
Labels: ci:docs-only

#1490 Fix SGEMM TN getsolutions gtest failure
  library/src/blas3/Tensile/Logic/asm_full/aquavanjaram942X/aquavanjaram942_Cijk_Alik_Bljk_SB.yaml
Labels: noHipblasLT

#1495 Fix link to device memory allocation in contributing doc 6.2 version …
  CONTRIBUTING.rst
Labels: ci:docs-only

#1496 Fix link to device memory allocation in contributing doc 6.2 version …
  CONTRIBUTING.rst
Labels: ci:docs-only
