Repository ROCm/rocBLAS, pull requests merged in 2025-05, with the labels that each got.

#1596 extend quick return cases for set get vector
  .jenkins/common.groovy
  clients/common/CMakeLists.txt
  clients/include/testing_set_get_matrix.hpp
  clients/include/testing_set_get_matrix_async.hpp
  clients/include/testing_set_get_vector.hpp
  clients/include/testing_set_get_vector_async.hpp
Labels: noHipblasLT, ci:asan, noTensile

#1593 Swdev 529952 base 950 kernel choices
  clients/gtest/asum_gtest.yaml
  clients/gtest/copy_gtest.yaml
  clients/gtest/dgmm_gtest.yaml
  clients/gtest/gbmv_gtest.yaml
  clients/gtest/geam_gtest.yaml
  clients/gtest/gemm_gtest.yaml
  clients/gtest/gemmt_gtest.yaml
  clients/gtest/gemv_gtest.yaml
  clients/gtest/ger_gtest.yaml
  clients/gtest/hbmv_gtest.yaml
  clients/gtest/hemm_gtest.yaml
  clients/gtest/hemv_gtest.yaml
  clients/gtest/her2_gtest.yaml
  clients/gtest/her2k_gtest.yaml
  clients/gtest/her_gtest.yaml
  clients/gtest/herk_gtest.yaml
  clients/gtest/herkx_gtest.yaml
  clients/gtest/hpmv_gtest.yaml
  clients/gtest/iamax_iamin_gtest.yaml
  clients/gtest/nrm2_gtest.yaml
  clients/gtest/rot_gtest.yaml
  clients/gtest/sbmv_gtest.yaml
  clients/gtest/scal_gtest.yaml
  clients/gtest/spmv_gtest.yaml
  clients/gtest/swap_gtest.yaml
  clients/gtest/symm_gtest.yaml
  clients/gtest/symv_gtest.yaml
  clients/gtest/syr2_gtest.yaml
  clients/gtest/syr2k_gtest.yaml
  clients/gtest/syr_gtest.yaml
  clients/gtest/syrk_gtest.yaml
  clients/gtest/syrkx_gtest.yaml
  clients/gtest/tbmv_gtest.yaml
  clients/gtest/tbsv_gtest.yaml
  clients/gtest/tpmv_gtest.yaml
  clients/gtest/tpsv_gtest.yaml
  clients/gtest/trmm_gtest.yaml
  clients/gtest/trmv_gtest.yaml
  clients/gtest/trsm_gtest.yaml
  clients/gtest/trsv_gtest.yaml
  clients/gtest/trtri_gtest.yaml
  library/src/blas1/rocblas_dot_kernels.hpp
  library/src/blas2/gemv_device.hpp
  library/src/blas2/rocblas_gemv_kernels.cpp
  library/src/blas2/rocblas_ger_kernels.hpp
  library/src/blas3/rocblas_dgmm_kernels.cpp
  library/src/blas3/rocblas_syrk_herk.hpp
Labels: ci:extended, gfx950

#1607 add build example for pip upgrade
  docs/install/Linux_Install_Guide.rst
Labels: ci:docs-only, documentation

#1595 Adding new Arch to default list
  library/src/hipblaslt_host.cpp
  library/src/include/handle.hpp
Labels: ci:extended, gfx950

#1609 update CHANGELOG.md for rocBLAS 5.0.0
  CHANGELOG.md
Labels: documentation

#1615 Update helper-functions.rst
  docs/reference/helper-functions.rst
Labels: ci:docs-only, documentation

#1619 Revert "Find 'rocm_smi' via find_package CONFIG (#1604)"
  clients/CMakeLists.txt
  clients/cmake/FindROCmSMI.cmake
Labels: ci:static-libraries

#1630 correcting install for compilation details (#1623)
  docs/conceptual/rocblas-design-notes.rst
  docs/install/Linux_Install_Guide.rst
Labels: ci:docs-only, documentation

#1626 beta API test reduction (#1622)
  clients/gtest/get_solutions_gtest.yaml
Labels: TestTensileOnly
