Repository ROCm/rocBLAS, pull requests merged in 2025-04, with the labels that each got.

#1565 correct scal test dispatch and simplify
  clients/gtest/blas1/scal_gtest.cpp
  clients/include/type_dispatch.hpp
Labels: noHipblasLT, noTensile, TestLevel1Only

#1568 ex3 duplicate test removal
  clients/gtest/gemm_batched_gtest.yaml
Labels: TestTensileOnly

#1569 ex3 duplicate test removal
  clients/gtest/gemm_batched_gtest.yaml
Labels: TestLevel3Only

#1567 tests reduced and moved to correct files
  clients/gtest/gemm_batched_gtest.yaml
  clients/gtest/gemm_gtest.yaml
  clients/gtest/gemm_strided_batched_gtest.yaml
Labels: TestTensileOnly

#1566 non verbose defaults
  docs/how-to/logging-in-rocblas.rst
  library/src/hipblaslt_host.cpp
  library/src/tensile_host.cpp
Labels: TestTensileOnly

#1573 Reorder rocBLAS deprecation notices
  docs/reference/deprecations.rst
Labels: ci:docs-only, documentation

#1576 Fixing Deprecation Doc
  docs/reference/deprecations.rst
Labels: ci:docs-only

#1575 stress tests fix gemm bad strides and misc cleanup
  clients/gtest/gemm_batched_gtest.yaml
  clients/gtest/gemm_strided_batched_gtest.yaml
Labels: weekly

#1577 Add copyright header for missing file
  library/src/logging.cpp
Labels: ci:docs-only, documentation

#1578 cherry-pick : Add copyright header for missing file
  library/src/logging.cpp
Labels: ci:docs-only

#1581 use ROCmCMakeBuildTools and fetch fallback
  CMakeLists.txt
  cmake/get-rocm-cmake.cmake
Labels: noTensile, TestLevel1Only

#1586 match clearer CI label added in rocSOLVER
  .jenkins/common.groovy
Labels: noHipblasLT, noTensile, TestLevel1Only, gfxall

#1587 ignore line end error
  CMakeLists.txt
Labels: ci:codecoverage

#1564 enable batched hipblaslt
  clients/gtest/get_solutions_gtest.yaml
  clients/include/blas_ex/testing_gemm_batched_ex_get_solutions.hpp
  clients/include/blas_ex/testing_gemm_ex_get_solutions.hpp
  clients/include/blas_ex/testing_gemm_strided_batched_ex_get_solutions.hpp
  library/src/handle.cpp
  library/src/hipblaslt_host.cpp
  library/src/include/handle.hpp
  library/src/tensile_host.cpp
Labels: ci:extended

#1585 logging test coverage for half APIs
  clients/gtest/logging_mode_gtest.cpp
  clients/gtest/logging_mode_gtest.yaml
  clients/include/testing_logging.hpp
Labels: ci:codecoverage

#1588 turn off c++17 extension warning for library
  library/CMakeLists.txt
Labels: noHipblasLT, noTensile, TestLevel1Only, gfx950

#1589 code coverage add profiling
  rtest.xml
Labels: noHipblasLT, ci:codecoverage, noTensile
