Repository ROCm/rocBLAS, pull requests merged in 2025-01, with the labels that each got.

#1539 fix dot large N batched bug (#2836)
  clients/gtest/blas1_gtest.yaml
  clients/include/blas_ex/testing_dot_batched_ex.hpp
  clients/include/blas_ex/testing_dot_ex.hpp
  clients/include/blas_ex/testing_dot_strided_batched_ex.hpp
  clients/include/near.hpp
  library/src/blas1/rocblas_dot_kernels.hpp
Labels: noHipblasLT

#1541 update categories (#2843)
  CHANGELOG.md
Labels: noCI, ci:docs-only

#1542 Fix static build errors
  clients/benchmarks/CMakeLists.txt
  clients/common/CMakeLists.txt
  clients/samples/CMakeLists.txt
  library/src/CMakeLists.txt
Labels: ci:static-libraries
