Repository ROCm/rocBLAS, pull requests merged in 2025-06, with the labels that each got.

#1633 adapt to hipblaslt API change
  library/src/hipblaslt_host.cpp
Labels: TestTensileOnly, gfx950

#1627 Cherry-pick to release/rocm-rel-6.4: Refactor rocBLAS documentation
  Acknowledgement.rst
  docs/conceptual/rocblas-design-notes.rst
  docs/conf.py
  docs/how-to/Contributors_Guide.rst
  docs/how-to/Programmers_Guide.rst
  docs/how-to/how-to.rst
  docs/how-to/logging-in-rocblas.rst
  docs/how-to/what-is-rocblas.rst
  docs/index.rst
  docs/install/Linux_Install_Guide.rst
  docs/install/Windows_Install_Guide.rst
  docs/install/install.rst
  docs/reference/API_Reference-Guide.rst
  docs/reference/acknowledge.rst
  docs/reference/beta-features.rst
  docs/reference/datatypes.rst
  docs/reference/deprecations.rst
  docs/reference/enumerations.rst
  docs/reference/extension.rst
  docs/reference/helper-functions.rst
  docs/reference/level-1.rst
  docs/reference/level-2.rst
  docs/reference/level-3.rst
  docs/reference/logging.rst
  docs/reference/memory-alloc.rst
  docs/sphinx/_toc.yml.in
  docs/what-is-rocblas.rst
Labels: ci:docs-only, documentation

#1635 Hotfix hipBLASLt API 1.0.0
  CMakeLists.txt
  library/src/hipblaslt_host.cpp
Labels: TestTensileOnly

#1636 disable c++17 ext warning in clients
  clients/common/CMakeLists.txt
  clients/samples/CMakeLists.txt
Labels: noHipblasLT, noTensile, TestLevel1Only

#1637 Update tensile tag
  tensile_tag.txt
Labels: TestLevel3Only

#1645 SWDEV-537656 - Add include for assert in example_user_driven_tuning
  clients/samples/example_user_driven_tuning.cpp
Labels: TestLevel1Only

#1647 SWDEV-537656 - Add include for assert in example_user_driven_tuning (…
  clients/samples/example_user_driven_tuning.cpp
Labels: TestLevel1Only

#1648 Zero imag portion of diagonal in syrk/herk
  clients/include/blas3/testing_herk.hpp
  clients/include/blas3/testing_herk_batched.hpp
  clients/include/blas3/testing_herk_strided_batched.hpp
  library/src/blas3/herk_syrk_device.hpp
  library/src/blas3/rocblas_syrk_herk_kernels.cpp
Labels: gfx942, TestTensileOnly

#1651 Zero imag portion of diagonal in syrk/herk (#1648)
  CHANGELOG.md
  CMakeLists.txt
  clients/include/blas3/testing_herk.hpp
  clients/include/blas3/testing_herk_batched.hpp
  clients/include/blas3/testing_herk_strided_batched.hpp
  library/src/blas3/herk_syrk_device.hpp
  library/src/blas3/rocblas_syrk_herk_kernels.cpp
Labels: gfx942, TestTensileOnly

#1650 Zero imag portion of diagonal in syrk/herk (#1648)
  CHANGELOG.md
  clients/include/blas3/testing_herk.hpp
  clients/include/blas3/testing_herk_batched.hpp
  clients/include/blas3/testing_herk_strided_batched.hpp
  library/src/blas3/herk_syrk_device.hpp
  library/src/blas3/rocblas_syrk_herk_kernels.cpp
Labels: gfx942, TestTensileOnly

#1655 add version detail to aid analysis
  clients/common/client_utility.cpp
Labels: TestLevel1Only

#1658 fix warnings
  clients/include/near.hpp
  clients/include/rocblas.hpp
  clients/include/rocblas_arguments.hpp
  clients/include/testing_logging.hpp
  library/include/internal/rocblas-complex-types.h
  library/src/blas2/rocblas_trsv_kernels.cpp
  library/src/include/utility.hpp
Labels: noHipblasLT

#1657 float double and all complex using Tensile on 950
  library/src/include/utility.hpp
  library/src/rocblas_auxiliary.cpp
  library/src/tensile_host.cpp
Labels: TestTensileOnly, gfx950
